server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://rs-mortgage-aws.civxewyb4pfe.us-west-2.rds.amazonaws.com:3306/rs_ecommerce
    username: admin
    password: admin1973
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


management:
  server:
    port: 8093
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
